### ISSUE TITLE
PokeGOAOI-Java has changed

### ISSUE THREAD

**Issue by fegkay15** [finelime/PokeMap#1]
As the title states, PokeGOAPI for Java has changed a bit so the code here doesn't accept the current version. So I was wondering if you could make it known which commit to go back to so that the correct version can be cloned rather than what is current.

**Comment by joeylemon** [comment]
I updated the git to the latest version using the new Java API, if that works for you. I don't remember exactly which commit I used when I first uploaded this

**Comment by fegkay15** [comment]
Yeah, that helps me. Quick question though, was it the development branch or master branch?

**Comment by joeylemon** [comment]
I believe it was the development branch. But again, I might be wrong, sorry!

**Comment by fegkay15** [comment]
It's no big deal. I'll clone both of them and see which one works. Thank you!
